// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.2
// source: grpctest/grpc_test.proto

package grpctest

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GrpcTestClient is the client API for GrpcTest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrpcTestClient interface {
	// A simple RPC.
	//
	// Obtains the feature at a given position.
	//
	// A feature with an empty name is returned if there's no feature at the given
	// position.
	GetFeature(ctx context.Context, in *Point, opts ...grpc.CallOption) (*Feature, error)
	// A server-to-client streaming RPC.
	//
	// Obtains the Features available within the given Rectangle.  Results are
	// streamed rather than returned at once (e.g. in a response message with a
	// repeated field), as the rectangle may cover a large area and contain a
	// huge number of features.
	ListFeatures(ctx context.Context, in *Rectangle, opts ...grpc.CallOption) (GrpcTest_ListFeaturesClient, error)
	// A client-to-server streaming RPC.
	//
	// Accepts a stream of Points on a route being traversed, returning a
	// RouteSummary when traversal is completed.
	RecordRoute(ctx context.Context, opts ...grpc.CallOption) (GrpcTest_RecordRouteClient, error)
	// A Bidirectional streaming RPC.
	//
	// Accepts a stream of RouteNotes sent while a route is being traversed,
	// while receiving other RouteNotes (e.g. from other users).
	RouteChat(ctx context.Context, opts ...grpc.CallOption) (GrpcTest_RouteChatClient, error)
}

type grpcTestClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcTestClient(cc grpc.ClientConnInterface) GrpcTestClient {
	return &grpcTestClient{cc}
}

func (c *grpcTestClient) GetFeature(ctx context.Context, in *Point, opts ...grpc.CallOption) (*Feature, error) {
	out := new(Feature)
	err := c.cc.Invoke(ctx, "/grpctest.GrpcTest/GetFeature", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcTestClient) ListFeatures(ctx context.Context, in *Rectangle, opts ...grpc.CallOption) (GrpcTest_ListFeaturesClient, error) {
	stream, err := c.cc.NewStream(ctx, &GrpcTest_ServiceDesc.Streams[0], "/grpctest.GrpcTest/ListFeatures", opts...)
	if err != nil {
		return nil, err
	}
	x := &grpcTestListFeaturesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GrpcTest_ListFeaturesClient interface {
	Recv() (*Feature, error)
	grpc.ClientStream
}

type grpcTestListFeaturesClient struct {
	grpc.ClientStream
}

func (x *grpcTestListFeaturesClient) Recv() (*Feature, error) {
	m := new(Feature)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *grpcTestClient) RecordRoute(ctx context.Context, opts ...grpc.CallOption) (GrpcTest_RecordRouteClient, error) {
	stream, err := c.cc.NewStream(ctx, &GrpcTest_ServiceDesc.Streams[1], "/grpctest.GrpcTest/RecordRoute", opts...)
	if err != nil {
		return nil, err
	}
	x := &grpcTestRecordRouteClient{stream}
	return x, nil
}

type GrpcTest_RecordRouteClient interface {
	Send(*Point) error
	CloseAndRecv() (*RouteSummary, error)
	grpc.ClientStream
}

type grpcTestRecordRouteClient struct {
	grpc.ClientStream
}

func (x *grpcTestRecordRouteClient) Send(m *Point) error {
	return x.ClientStream.SendMsg(m)
}

func (x *grpcTestRecordRouteClient) CloseAndRecv() (*RouteSummary, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(RouteSummary)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *grpcTestClient) RouteChat(ctx context.Context, opts ...grpc.CallOption) (GrpcTest_RouteChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &GrpcTest_ServiceDesc.Streams[2], "/grpctest.GrpcTest/RouteChat", opts...)
	if err != nil {
		return nil, err
	}
	x := &grpcTestRouteChatClient{stream}
	return x, nil
}

type GrpcTest_RouteChatClient interface {
	Send(*RouteNote) error
	Recv() (*RouteNote, error)
	grpc.ClientStream
}

type grpcTestRouteChatClient struct {
	grpc.ClientStream
}

func (x *grpcTestRouteChatClient) Send(m *RouteNote) error {
	return x.ClientStream.SendMsg(m)
}

func (x *grpcTestRouteChatClient) Recv() (*RouteNote, error) {
	m := new(RouteNote)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GrpcTestServer is the server API for GrpcTest service.
// All implementations must embed UnimplementedGrpcTestServer
// for forward compatibility
type GrpcTestServer interface {
	// A simple RPC.
	//
	// Obtains the feature at a given position.
	//
	// A feature with an empty name is returned if there's no feature at the given
	// position.
	GetFeature(context.Context, *Point) (*Feature, error)
	// A server-to-client streaming RPC.
	//
	// Obtains the Features available within the given Rectangle.  Results are
	// streamed rather than returned at once (e.g. in a response message with a
	// repeated field), as the rectangle may cover a large area and contain a
	// huge number of features.
	ListFeatures(*Rectangle, GrpcTest_ListFeaturesServer) error
	// A client-to-server streaming RPC.
	//
	// Accepts a stream of Points on a route being traversed, returning a
	// RouteSummary when traversal is completed.
	RecordRoute(GrpcTest_RecordRouteServer) error
	// A Bidirectional streaming RPC.
	//
	// Accepts a stream of RouteNotes sent while a route is being traversed,
	// while receiving other RouteNotes (e.g. from other users).
	RouteChat(GrpcTest_RouteChatServer) error
	mustEmbedUnimplementedGrpcTestServer()
}

// UnimplementedGrpcTestServer must be embedded to have forward compatible implementations.
type UnimplementedGrpcTestServer struct {
}

func (UnimplementedGrpcTestServer) GetFeature(context.Context, *Point) (*Feature, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeature not implemented")
}
func (UnimplementedGrpcTestServer) ListFeatures(*Rectangle, GrpcTest_ListFeaturesServer) error {
	return status.Errorf(codes.Unimplemented, "method ListFeatures not implemented")
}
func (UnimplementedGrpcTestServer) RecordRoute(GrpcTest_RecordRouteServer) error {
	return status.Errorf(codes.Unimplemented, "method RecordRoute not implemented")
}
func (UnimplementedGrpcTestServer) RouteChat(GrpcTest_RouteChatServer) error {
	return status.Errorf(codes.Unimplemented, "method RouteChat not implemented")
}
func (UnimplementedGrpcTestServer) mustEmbedUnimplementedGrpcTestServer() {}

// UnsafeGrpcTestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrpcTestServer will
// result in compilation errors.
type UnsafeGrpcTestServer interface {
	mustEmbedUnimplementedGrpcTestServer()
}

func RegisterGrpcTestServer(s grpc.ServiceRegistrar, srv GrpcTestServer) {
	s.RegisterService(&GrpcTest_ServiceDesc, srv)
}

func _GrpcTest_GetFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Point)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcTestServer).GetFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpctest.GrpcTest/GetFeature",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcTestServer).GetFeature(ctx, req.(*Point))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcTest_ListFeatures_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Rectangle)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GrpcTestServer).ListFeatures(m, &grpcTestListFeaturesServer{stream})
}

type GrpcTest_ListFeaturesServer interface {
	Send(*Feature) error
	grpc.ServerStream
}

type grpcTestListFeaturesServer struct {
	grpc.ServerStream
}

func (x *grpcTestListFeaturesServer) Send(m *Feature) error {
	return x.ServerStream.SendMsg(m)
}

func _GrpcTest_RecordRoute_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GrpcTestServer).RecordRoute(&grpcTestRecordRouteServer{stream})
}

type GrpcTest_RecordRouteServer interface {
	SendAndClose(*RouteSummary) error
	Recv() (*Point, error)
	grpc.ServerStream
}

type grpcTestRecordRouteServer struct {
	grpc.ServerStream
}

func (x *grpcTestRecordRouteServer) SendAndClose(m *RouteSummary) error {
	return x.ServerStream.SendMsg(m)
}

func (x *grpcTestRecordRouteServer) Recv() (*Point, error) {
	m := new(Point)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GrpcTest_RouteChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GrpcTestServer).RouteChat(&grpcTestRouteChatServer{stream})
}

type GrpcTest_RouteChatServer interface {
	Send(*RouteNote) error
	Recv() (*RouteNote, error)
	grpc.ServerStream
}

type grpcTestRouteChatServer struct {
	grpc.ServerStream
}

func (x *grpcTestRouteChatServer) Send(m *RouteNote) error {
	return x.ServerStream.SendMsg(m)
}

func (x *grpcTestRouteChatServer) Recv() (*RouteNote, error) {
	m := new(RouteNote)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GrpcTest_ServiceDesc is the grpc.ServiceDesc for GrpcTest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrpcTest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpctest.GrpcTest",
	HandlerType: (*GrpcTestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFeature",
			Handler:    _GrpcTest_GetFeature_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListFeatures",
			Handler:       _GrpcTest_ListFeatures_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RecordRoute",
			Handler:       _GrpcTest_RecordRoute_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "RouteChat",
			Handler:       _GrpcTest_RouteChat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpctest/grpc_test.proto",
}
