// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.2
// source: simplegrpc/simple_grpc.proto

package simplegrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SimpleGrpcClient is the client API for SimpleGrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SimpleGrpcClient interface {
	// A simple RPC.
	//
	// Obtains the feature at a given position.
	//
	// A feature with an empty name is returned if there's no feature at the given
	// position.
	GetFeature(ctx context.Context, in *Point, opts ...grpc.CallOption) (*Feature, error)
	// A server-to-client streaming RPC.
	//
	// Obtains the Features available within the given Rectangle.  Results are
	// streamed rather than returned at once (e.g. in a response message with a
	// repeated field), as the rectangle may cover a large area and contain a
	// huge number of features.
	ListFeatures(ctx context.Context, in *Rectangle, opts ...grpc.CallOption) (SimpleGrpc_ListFeaturesClient, error)
	// A client-to-server streaming RPC.
	//
	// Accepts a stream of Points on a route being traversed, returning a
	// RouteSummary when traversal is completed.
	RecordRoute(ctx context.Context, opts ...grpc.CallOption) (SimpleGrpc_RecordRouteClient, error)
	// A Bidirectional streaming RPC.
	//
	// Accepts a stream of RouteNotes sent while a route is being traversed,
	// while receiving other RouteNotes (e.g. from other users).
	RouteChat(ctx context.Context, opts ...grpc.CallOption) (SimpleGrpc_RouteChatClient, error)
}

type simpleGrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewSimpleGrpcClient(cc grpc.ClientConnInterface) SimpleGrpcClient {
	return &simpleGrpcClient{cc}
}

func (c *simpleGrpcClient) GetFeature(ctx context.Context, in *Point, opts ...grpc.CallOption) (*Feature, error) {
	out := new(Feature)
	err := c.cc.Invoke(ctx, "/simplegrpc.SimpleGrpc/GetFeature", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simpleGrpcClient) ListFeatures(ctx context.Context, in *Rectangle, opts ...grpc.CallOption) (SimpleGrpc_ListFeaturesClient, error) {
	stream, err := c.cc.NewStream(ctx, &SimpleGrpc_ServiceDesc.Streams[0], "/simplegrpc.SimpleGrpc/ListFeatures", opts...)
	if err != nil {
		return nil, err
	}
	x := &simpleGrpcListFeaturesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SimpleGrpc_ListFeaturesClient interface {
	Recv() (*Feature, error)
	grpc.ClientStream
}

type simpleGrpcListFeaturesClient struct {
	grpc.ClientStream
}

func (x *simpleGrpcListFeaturesClient) Recv() (*Feature, error) {
	m := new(Feature)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *simpleGrpcClient) RecordRoute(ctx context.Context, opts ...grpc.CallOption) (SimpleGrpc_RecordRouteClient, error) {
	stream, err := c.cc.NewStream(ctx, &SimpleGrpc_ServiceDesc.Streams[1], "/simplegrpc.SimpleGrpc/RecordRoute", opts...)
	if err != nil {
		return nil, err
	}
	x := &simpleGrpcRecordRouteClient{stream}
	return x, nil
}

type SimpleGrpc_RecordRouteClient interface {
	Send(*Point) error
	CloseAndRecv() (*RouteSummary, error)
	grpc.ClientStream
}

type simpleGrpcRecordRouteClient struct {
	grpc.ClientStream
}

func (x *simpleGrpcRecordRouteClient) Send(m *Point) error {
	return x.ClientStream.SendMsg(m)
}

func (x *simpleGrpcRecordRouteClient) CloseAndRecv() (*RouteSummary, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(RouteSummary)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *simpleGrpcClient) RouteChat(ctx context.Context, opts ...grpc.CallOption) (SimpleGrpc_RouteChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &SimpleGrpc_ServiceDesc.Streams[2], "/simplegrpc.SimpleGrpc/RouteChat", opts...)
	if err != nil {
		return nil, err
	}
	x := &simpleGrpcRouteChatClient{stream}
	return x, nil
}

type SimpleGrpc_RouteChatClient interface {
	Send(*RouteNote) error
	Recv() (*RouteNote, error)
	grpc.ClientStream
}

type simpleGrpcRouteChatClient struct {
	grpc.ClientStream
}

func (x *simpleGrpcRouteChatClient) Send(m *RouteNote) error {
	return x.ClientStream.SendMsg(m)
}

func (x *simpleGrpcRouteChatClient) Recv() (*RouteNote, error) {
	m := new(RouteNote)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SimpleGrpcServer is the server API for SimpleGrpc service.
// All implementations must embed UnimplementedSimpleGrpcServer
// for forward compatibility
type SimpleGrpcServer interface {
	// A simple RPC.
	//
	// Obtains the feature at a given position.
	//
	// A feature with an empty name is returned if there's no feature at the given
	// position.
	GetFeature(context.Context, *Point) (*Feature, error)
	// A server-to-client streaming RPC.
	//
	// Obtains the Features available within the given Rectangle.  Results are
	// streamed rather than returned at once (e.g. in a response message with a
	// repeated field), as the rectangle may cover a large area and contain a
	// huge number of features.
	ListFeatures(*Rectangle, SimpleGrpc_ListFeaturesServer) error
	// A client-to-server streaming RPC.
	//
	// Accepts a stream of Points on a route being traversed, returning a
	// RouteSummary when traversal is completed.
	RecordRoute(SimpleGrpc_RecordRouteServer) error
	// A Bidirectional streaming RPC.
	//
	// Accepts a stream of RouteNotes sent while a route is being traversed,
	// while receiving other RouteNotes (e.g. from other users).
	RouteChat(SimpleGrpc_RouteChatServer) error
	mustEmbedUnimplementedSimpleGrpcServer()
}

// UnimplementedSimpleGrpcServer must be embedded to have forward compatible implementations.
type UnimplementedSimpleGrpcServer struct {
}

func (UnimplementedSimpleGrpcServer) GetFeature(context.Context, *Point) (*Feature, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeature not implemented")
}
func (UnimplementedSimpleGrpcServer) ListFeatures(*Rectangle, SimpleGrpc_ListFeaturesServer) error {
	return status.Errorf(codes.Unimplemented, "method ListFeatures not implemented")
}
func (UnimplementedSimpleGrpcServer) RecordRoute(SimpleGrpc_RecordRouteServer) error {
	return status.Errorf(codes.Unimplemented, "method RecordRoute not implemented")
}
func (UnimplementedSimpleGrpcServer) RouteChat(SimpleGrpc_RouteChatServer) error {
	return status.Errorf(codes.Unimplemented, "method RouteChat not implemented")
}
func (UnimplementedSimpleGrpcServer) mustEmbedUnimplementedSimpleGrpcServer() {}

// UnsafeSimpleGrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SimpleGrpcServer will
// result in compilation errors.
type UnsafeSimpleGrpcServer interface {
	mustEmbedUnimplementedSimpleGrpcServer()
}

func RegisterSimpleGrpcServer(s grpc.ServiceRegistrar, srv SimpleGrpcServer) {
	s.RegisterService(&SimpleGrpc_ServiceDesc, srv)
}

func _SimpleGrpc_GetFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Point)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimpleGrpcServer).GetFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/simplegrpc.SimpleGrpc/GetFeature",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimpleGrpcServer).GetFeature(ctx, req.(*Point))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimpleGrpc_ListFeatures_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Rectangle)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SimpleGrpcServer).ListFeatures(m, &simpleGrpcListFeaturesServer{stream})
}

type SimpleGrpc_ListFeaturesServer interface {
	Send(*Feature) error
	grpc.ServerStream
}

type simpleGrpcListFeaturesServer struct {
	grpc.ServerStream
}

func (x *simpleGrpcListFeaturesServer) Send(m *Feature) error {
	return x.ServerStream.SendMsg(m)
}

func _SimpleGrpc_RecordRoute_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SimpleGrpcServer).RecordRoute(&simpleGrpcRecordRouteServer{stream})
}

type SimpleGrpc_RecordRouteServer interface {
	SendAndClose(*RouteSummary) error
	Recv() (*Point, error)
	grpc.ServerStream
}

type simpleGrpcRecordRouteServer struct {
	grpc.ServerStream
}

func (x *simpleGrpcRecordRouteServer) SendAndClose(m *RouteSummary) error {
	return x.ServerStream.SendMsg(m)
}

func (x *simpleGrpcRecordRouteServer) Recv() (*Point, error) {
	m := new(Point)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _SimpleGrpc_RouteChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SimpleGrpcServer).RouteChat(&simpleGrpcRouteChatServer{stream})
}

type SimpleGrpc_RouteChatServer interface {
	Send(*RouteNote) error
	Recv() (*RouteNote, error)
	grpc.ServerStream
}

type simpleGrpcRouteChatServer struct {
	grpc.ServerStream
}

func (x *simpleGrpcRouteChatServer) Send(m *RouteNote) error {
	return x.ServerStream.SendMsg(m)
}

func (x *simpleGrpcRouteChatServer) Recv() (*RouteNote, error) {
	m := new(RouteNote)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SimpleGrpc_ServiceDesc is the grpc.ServiceDesc for SimpleGrpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SimpleGrpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "simplegrpc.SimpleGrpc",
	HandlerType: (*SimpleGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFeature",
			Handler:    _SimpleGrpc_GetFeature_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListFeatures",
			Handler:       _SimpleGrpc_ListFeatures_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RecordRoute",
			Handler:       _SimpleGrpc_RecordRoute_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "RouteChat",
			Handler:       _SimpleGrpc_RouteChat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "simplegrpc/simple_grpc.proto",
}
